name: clang format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format_check:
    name: Check Code Formatting
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      
      - name: Install clang-format
        run: |
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          echo "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-22 main" | sudo tee /etc/apt/sources.list.d/llvm.list
          sudo apt-get update && sudo apt-get install -y clang-format-22
        
      - name: Check code formatting
        run:  find ./ \( -name '*.cpp' -o -name '*.h' \) -not \( -path '*/build/*' -o -path '*/thirdparty/*' \) -exec clang-format-22 -style=Google -output-replacements-xml {} + -print | grep "<replacement " && exit 1 || exit 0
